language: python

python:
  - 2.6
  - 2.7
  - 3.5

services: psql

env:
  - DJANGO=1.10.2

before_install:
  - export DJANGO_SETTINGS_MODULE=maintt.settings
  - export PYTHONPATH=$HOME/builds/andelaOSP/maintt/maintt
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py migrate