language: python

python:
  - 2.7
  - 3.5

services:
  - mysql

env:
  - DJANGO=1.10.2

before_install:
  - export DJANGO_SETTINGS_MODULE=maintt.settings
  - export PYTHONPATH=$HOME/builds/andelaOSP/maintt/maintt

install:
  - cd maintt && pip install -r requirements.txt

script:
  - python manage.py migrate
  - python manage.py test tests