language: python

sudo: required

python:
  - 2.7
  - 3.5

services:
  - mysql

env:
  - DJANGO=1.10.2

before_install:
  - export DJANGO_SETTINGS_MODULE=maintt.settings
  - export PYTHONPATH=$HOME/builds/andelaOSP/maintt/maintt

install:
  - cd maintt && pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE maintt;'
  - cd maintt && mv .env.example .env
  - ls

script:
  - cd maintt && python manage.py migrate
  - cd maintt && python manage.py test tests